#!/usr/bin/env bash
# This script displays list of currently running processes
# must show all processes, for all users, including those which might not have a TTY
# Display a user-oriented format
# show process hierarchy

ps -a -x -u -f
